### ISSUE TITLE
Features and priorities meta issue

### ISSUE THREAD

**Issue by Robinlovelace** [acteng/atip#3]
## All implementations

- [x] It's where they are that's importat
- [x] Concept + documentation development
  - [ ] Communicate it's place in context of 3 levels, sketch, Meso tool, Micro (TBC on names)

- [x] Sketching areas
- [ ] Sketching crossings
- [ ] Sketching routes

## Route tool

Minimum:

- [ ] % with different types
- [ ] Average width
- [ ] design volume?

### Evaluation

Currently the plan is to do most of this in separate tools:

- [x] Many evaluation metrics for area tool available in LTN tool
- [ ] Metric of 'leakiness' 
- [ ] % who live in a liveable/LTN area? (could be done in web app with population and existing LTN data from CycleStreets

## atipshiny implementation: https://shiny.robinlovelace.net/atipshiny/

- [x] Remove revenue
- [x] Remove sliders
- [x] Planned delivery date in financial year

# Next steps

- [x] Update the shiny version with updates from this
- Sketch the route design tool in shiny/JS/other
- Sketch the crossings tool in shiny/JS/other

**Comment by Robinlovelace** [comment]
Closing for now, gone a bit stale.
