### ISSUE TITLE
Plan Your Active Travel Scheme release checklist

### ISSUE THREAD

**Issue by Pete-Y-CS** [acteng/atip#546]
- [x]  Further changes for ACB as requested by Tom A
- [x]  Pen Test (currently scheduled for 28th-29th Nov)
- [x]  CAB (currently scheduled for 22nd Nov)
- [x]  Put accessibility statement on landing page
- [x]  Deploy to test env for pen test
- [x]  Deploy to prod after pen test
- [x]  Tutorial
- [x]  add .txt output instructions to tutorial
- [x]  privacy statement
- [x]  Issue/support email
- [x]  deploy to test
- [x]  highlight if user is on dev or test
- [x] Update data-prep manifest for all new buckets
- [x] Set up a permanent git branch to represent what's in prod
